[package]
name = "my-crate"
version = "0.1.0"
edition = "2021"
authors = ["shiyivei"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main"
path = "bin/main.rs"


[dependencies]
num_cpus = "1.15.0"
serde = "1.0.152"
toml = "0.7.1"
