[package]
name = "crate-pre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait ={version = "0.1.64",features = ["derive"]}
serde = "1.0.152"
url = "2.3.1"
