[package]
name = "dif-bin-and-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
num_cpus = "1.15.0"
rand = "0.8.5"
rayon = "1.6.1"
toml = "0.7.1"
